USE [master]
GO

/****** Object:  Database [CustomShopDB]    Script Date: 09/30/2021 18:42:48 ******/
CREATE DATABASE [CustomShopDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CustomShopDB', FILENAME = N'C:\Users\Judasz z Pogoni\CustomShopDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CustomShopDB_log', FILENAME = N'C:\Users\Judasz z Pogoni\CustomShopDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CustomShopDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CustomShopDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CustomShopDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CustomShopDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CustomShopDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CustomShopDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CustomShopDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CustomShopDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CustomShopDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CustomShopDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CustomShopDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CustomShopDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CustomShopDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CustomShopDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CustomShopDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CustomShopDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CustomShopDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CustomShopDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CustomShopDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CustomShopDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CustomShopDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CustomShopDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CustomShopDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CustomShopDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CustomShopDB] SET  MULTI_USER 
GO

ALTER DATABASE [CustomShopDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CustomShopDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CustomShopDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CustomShopDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CustomShopDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CustomShopDB] SET QUERY_STORE = OFF
GO

USE [CustomShopDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CustomShopDB] SET  READ_WRITE 
GO

